# Generated by Django 3.1.3 on 2020-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='', max_length=255, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
