# Generated by Django 3.1.3 on 2020-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_products_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='about',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.TextField(default='', verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(choices=[('C', 'Combo Caseiro'), ('F', 'Marmita Fit'), ('L', 'Marmita Low Carb')], max_length=1, verbose_name='tipo'),
        ),
    ]
