# Generated by Django 3.1.3 on 2020-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_auto_20201121_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(choices=[('combo', 'Combo Caseiro'), ('fit', 'Marmita Fit'), ('lowcarb', 'Marmita Low Carb')], max_length=255, verbose_name='tipo'),
        ),
    ]
