# Generated by Django 3.1.3 on 2020-11-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_auto_20201121_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
