# Generated by Django 3.1.3 on 2020-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('acompanhamentos', models.PositiveSmallIntegerField(default=0)),
                ('carnes', models.PositiveSmallIntegerField(default=0)),
                ('frangos', models.PositiveSmallIntegerField(default=0)),
                ('massas', models.PositiveSmallIntegerField(default=0)),
                ('peixe', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='preço')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('discount', models.BooleanField(default=False, verbose_name='desconto de 10%')),
            ],
        ),
        migrations.CreateModel(
            name='LowCarb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='preço')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('discount', models.BooleanField(default=False, verbose_name='desconto de 10%')),
            ],
            options={
                'verbose_name': 'Low Carb',
                'verbose_name_plural': 'Low Carbs',
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'acompanhamentos'), ('2', 'carnes'), ('3', 'frangos'), ('4', 'massas'), ('5', 'peixes')], max_length=1, verbose_name='tipo')),
                ('name', models.TextField(verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='preço')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('discount', models.BooleanField(default=False, verbose_name='desconto de 10%')),
            ],
            options={
                'verbose_name': 'Porção',
                'verbose_name_plural': 'Porções',
            },
        ),
    ]
