# Generated by Django 3.1.3 on 2020-12-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productgroup_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('discount', models.BooleanField(default=False, verbose_name='desconto (10%)')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.RenameModel(
            old_name='ProductGroup',
            new_name='ItemGroup',
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ItemType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemgroup', verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemtype', verbose_name='tipo'),
        ),
    ]
