# Generated by Django 3.1.3 on 2020-12-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201223_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='packge_amount',
            new_name='package',
        ),
    ]
