# Generated by Django 3.1.3 on 2021-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201223_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
    ]
