# Generated by Django 3.1.3 on 2021-01-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210102_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='min_order',
            field=models.SmallIntegerField(default=5, verbose_name='pedido mínimo'),
            preserve_default=False,
        ),
    ]
