# Generated by Django 3.1.3 on 2021-01-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_itemgroup_min_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='menu_page',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='página do cardápio'),
            preserve_default=False,
        ),
    ]
