# Generated by Django 3.1.3 on 2021-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210107_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='Fit',
        ),
        migrations.DeleteModel(
            name='LowCarb',
        ),
        migrations.DeleteModel(
            name='Portion',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='description',
            field=models.TextField(default=1, verbose_name='descrição (opcional)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='package',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='embalagem (ml)'),
        ),
    ]
