# Generated by Django 3.1.3 on 2021-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210108_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='imagem do grupo'),
            preserve_default=False,
        ),
    ]
