# Generated by Django 3.1.3 on 2021-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='grupo'),
        ),
    ]
